[package]
name = "grow"
version = "0.0.1"
authors = ["Felix Rath <felixr@archlinux.info>", "Felix Dietze <felix@beerleader.net>"]

# [dependencies.nphysics2df32]
# git = "https://github.com/sebcrozet/nphysics"

[dependencies.glium]
git = "https://github.com/futile/glium"



