[package]

name = "grow"
version = "0.0.1"
authors = ["Felix Rath <felixr@archlinux.info>", "Felix Dietze <felix@beerleader.net>"]

[dependencies.sdl2]

git = "https://github.com/AngryLawyer/rust-sdl2.git"
